// Generated by `pnpm db:types:local` from supabase/migrations. Do not edit.
// `pnpm db:types` (Supabase CLI, linked project) produces the same shape.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admin_users: {
        Row: {
          user_id: string;
          email: string;
          role: Database["public"]["Enums"]["admin_role"];
          created_at: string;
        };
        Insert: {
          user_id: string;
          email: string;
          role?: Database["public"]["Enums"]["admin_role"];
          created_at?: string;
        };
        Update: {
          user_id?: string;
          email?: string;
          role?: Database["public"]["Enums"]["admin_role"];
          created_at?: string;
        };
        Relationships: [
        ];
      };
      categories: {
        Row: {
          id: number;
          slug: string;
          name: string;
          description: string | null;
          image_path: string | null;
          sort_order: number;
          is_coming_soon: boolean;
          seo_title: string | null;
          seo_description: string | null;
          created_at: string;
        };
        Insert: {
          id?: never;
          slug: string;
          name: string;
          description?: string | null;
          image_path?: string | null;
          sort_order?: number;
          is_coming_soon?: boolean;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: never;
          slug?: string;
          name?: string;
          description?: string | null;
          image_path?: string | null;
          sort_order?: number;
          is_coming_soon?: boolean;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      contact_messages: {
        Row: {
          id: number;
          name: string;
          email: string | null;
          phone: string | null;
          message: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: never;
          name: string;
          email?: string | null;
          phone?: string | null;
          message: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: never;
          name?: string;
          email?: string | null;
          phone?: string | null;
          message?: string;
          is_read?: boolean;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      document_counters: {
        Row: {
          kind: string;
          period: string;
          last_value: number;
        };
        Insert: {
          kind: string;
          period: string;
          last_value?: number;
        };
        Update: {
          kind?: string;
          period?: string;
          last_value?: number;
        };
        Relationships: [
        ];
      };
      faqs: {
        Row: {
          id: number;
          question: string;
          answer: string;
          group_name: string | null;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          id?: never;
          question: string;
          answer: string;
          group_name?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          id?: never;
          question?: string;
          answer?: string;
          group_name?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [
        ];
      };
      gift_card_redemptions: {
        Row: {
          id: number;
          gift_card_id: number;
          order_id: string;
          amount: number;
          reversed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: never;
          gift_card_id: number;
          order_id: string;
          amount: number;
          reversed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: never;
          gift_card_id?: number;
          order_id?: string;
          amount?: number;
          reversed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "gift_card_redemptions_gift_card_id_fkey";
            columns: ["gift_card_id"];
            isOneToOne: false;
            referencedRelation: "gift_cards";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "gift_card_redemptions_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      gift_cards: {
        Row: {
          id: number;
          code: string;
          initial_balance: number;
          balance: number;
          expires_at: string | null;
          is_active: boolean;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: never;
          code: string;
          initial_balance: number;
          balance: number;
          expires_at?: string | null;
          is_active?: boolean;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: never;
          code?: string;
          initial_balance?: number;
          balance?: number;
          expires_at?: string | null;
          is_active?: boolean;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      hero_slides: {
        Row: {
          id: number;
          image_desktop_path: string;
          image_mobile_path: string;
          alt: string;
          label: string | null;
          link_url: string | null;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          id?: never;
          image_desktop_path: string;
          image_mobile_path: string;
          alt: string;
          label?: string | null;
          link_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          id?: never;
          image_desktop_path?: string;
          image_mobile_path?: string;
          alt?: string;
          label?: string | null;
          link_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [
        ];
      };
      lifestyle_tiles: {
        Row: {
          id: number;
          category_id: number | null;
          image_path: string;
          alt: string;
          caption: string | null;
          link_url: string | null;
          insert_after_position: number;
          span: number;
          is_active: boolean;
        };
        Insert: {
          id?: never;
          category_id?: number | null;
          image_path: string;
          alt: string;
          caption?: string | null;
          link_url?: string | null;
          insert_after_position: number;
          span?: number;
          is_active?: boolean;
        };
        Update: {
          id?: never;
          category_id?: number | null;
          image_path?: string;
          alt?: string;
          caption?: string | null;
          link_url?: string | null;
          insert_after_position?: number;
          span?: number;
          is_active?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "lifestyle_tiles_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      order_events: {
        Row: {
          id: number;
          order_id: string;
          type: Database["public"]["Enums"]["order_event_type"];
          from_value: string | null;
          to_value: string | null;
          note: string | null;
          actor_email: string | null;
          created_at: string;
        };
        Insert: {
          id?: never;
          order_id: string;
          type: Database["public"]["Enums"]["order_event_type"];
          from_value?: string | null;
          to_value?: string | null;
          note?: string | null;
          actor_email?: string | null;
          created_at?: string;
        };
        Update: {
          id?: never;
          order_id?: string;
          type?: Database["public"]["Enums"]["order_event_type"];
          from_value?: string | null;
          to_value?: string | null;
          note?: string | null;
          actor_email?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "order_events_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      order_items: {
        Row: {
          id: number;
          order_id: string;
          product_id: number | null;
          variant_label: string | null;
          name_snapshot: string;
          image_path_snapshot: string | null;
          unit_price: number;
          quantity: number;
          line_total: number;
        };
        Insert: {
          id?: never;
          order_id: string;
          product_id?: number | null;
          variant_label?: string | null;
          name_snapshot: string;
          image_path_snapshot?: string | null;
          unit_price: number;
          quantity: number;
          line_total: number;
        };
        Update: {
          id?: never;
          order_id?: string;
          product_id?: number | null;
          variant_label?: string | null;
          name_snapshot?: string;
          image_path_snapshot?: string | null;
          unit_price?: number;
          quantity?: number;
          line_total?: number;
        };
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_items_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          access_token: string;
          status: Database["public"]["Enums"]["order_status"];
          payment_method: Database["public"]["Enums"]["payment_method"];
          payment_status: Database["public"]["Enums"]["payment_status"];
          customer_name: string;
          email: string | null;
          phone: string;
          address_line1: string;
          address_line2: string | null;
          landmark: string | null;
          city: string;
          state: string;
          pincode: string;
          country: string;
          is_gift: boolean;
          gift_note: string | null;
          subtotal: number;
          gift_card_code: string | null;
          gift_card_amount: number;
          shipping_fee: number;
          gst_amount: number;
          total: number;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          invoice_number: string | null;
          courier_name: string | null;
          tracking_number: string | null;
          internal_notes: string | null;
          stock_released_at: string | null;
          created_at: string;
          paid_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          access_token?: string;
          status?: Database["public"]["Enums"]["order_status"];
          payment_method: Database["public"]["Enums"]["payment_method"];
          payment_status?: Database["public"]["Enums"]["payment_status"];
          customer_name: string;
          email?: string | null;
          phone: string;
          address_line1: string;
          address_line2?: string | null;
          landmark?: string | null;
          city: string;
          state: string;
          pincode: string;
          country?: string;
          is_gift?: boolean;
          gift_note?: string | null;
          subtotal: number;
          gift_card_code?: string | null;
          gift_card_amount?: number;
          shipping_fee?: number;
          gst_amount?: number;
          total: number;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          invoice_number?: string | null;
          courier_name?: string | null;
          tracking_number?: string | null;
          internal_notes?: string | null;
          stock_released_at?: string | null;
          created_at?: string;
          paid_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          access_token?: string;
          status?: Database["public"]["Enums"]["order_status"];
          payment_method?: Database["public"]["Enums"]["payment_method"];
          payment_status?: Database["public"]["Enums"]["payment_status"];
          customer_name?: string;
          email?: string | null;
          phone?: string;
          address_line1?: string;
          address_line2?: string | null;
          landmark?: string | null;
          city?: string;
          state?: string;
          pincode?: string;
          country?: string;
          is_gift?: boolean;
          gift_note?: string | null;
          subtotal?: number;
          gift_card_code?: string | null;
          gift_card_amount?: number;
          shipping_fee?: number;
          gst_amount?: number;
          total?: number;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          invoice_number?: string | null;
          courier_name?: string | null;
          tracking_number?: string | null;
          internal_notes?: string | null;
          stock_released_at?: string | null;
          created_at?: string;
          paid_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      pages: {
        Row: {
          id: number;
          slug: string;
          title: string;
          body: string;
          seo_title: string | null;
          seo_description: string | null;
          updated_at: string;
        };
        Insert: {
          id?: never;
          slug: string;
          title: string;
          body?: string;
          seo_title?: string | null;
          seo_description?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: never;
          slug?: string;
          title?: string;
          body?: string;
          seo_title?: string | null;
          seo_description?: string | null;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      product_images: {
        Row: {
          id: number;
          product_id: number;
          storage_path: string;
          role: Database["public"]["Enums"]["image_role"];
          alt: string;
          sort_order: number;
          width: number | null;
          height: number | null;
          blur_data_url: string | null;
        };
        Insert: {
          id?: never;
          product_id: number;
          storage_path: string;
          role: Database["public"]["Enums"]["image_role"];
          alt: string;
          sort_order?: number;
          width?: number | null;
          height?: number | null;
          blur_data_url?: string | null;
        };
        Update: {
          id?: never;
          product_id?: number;
          storage_path?: string;
          role?: Database["public"]["Enums"]["image_role"];
          alt?: string;
          sort_order?: number;
          width?: number | null;
          height?: number | null;
          blur_data_url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      product_relations: {
        Row: {
          product_id: number;
          related_product_id: number;
          kind: Database["public"]["Enums"]["relation_kind"];
          sort_order: number;
        };
        Insert: {
          product_id: number;
          related_product_id: number;
          kind: Database["public"]["Enums"]["relation_kind"];
          sort_order?: number;
        };
        Update: {
          product_id?: number;
          related_product_id?: number;
          kind?: Database["public"]["Enums"]["relation_kind"];
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "product_relations_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "product_relations_related_product_id_fkey";
            columns: ["related_product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      product_variants: {
        Row: {
          id: number;
          product_id: number;
          label: string;
          colour: string | null;
          stock_qty: number;
          sort_order: number;
        };
        Insert: {
          id?: never;
          product_id: number;
          label: string;
          colour?: string | null;
          stock_qty?: number;
          sort_order?: number;
        };
        Update: {
          id?: never;
          product_id?: number;
          label?: string;
          colour?: string | null;
          stock_qty?: number;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "product_variants_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      products: {
        Row: {
          id: number;
          slug: string;
          name: string;
          category_id: number;
          short_description: string | null;
          description: string | null;
          price: number | null;
          materials: string[];
          stones: string[];
          colours: string[];
          styles: string[];
          closure: string | null;
          chain_length: string | null;
          care_override: string | null;
          is_published: boolean;
          is_new_arrival: boolean;
          is_best_seller: boolean;
          is_gift_for_her: boolean;
          is_hero: boolean;
          stock_qty: number;
          merch_position: number | null;
          new_arrival_position: number | null;
          best_seller_position: number | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: never;
          slug: string;
          name: string;
          category_id: number;
          short_description?: string | null;
          description?: string | null;
          price?: number | null;
          materials?: string[];
          stones?: string[];
          colours?: string[];
          styles?: string[];
          closure?: string | null;
          chain_length?: string | null;
          care_override?: string | null;
          is_published?: boolean;
          is_new_arrival?: boolean;
          is_best_seller?: boolean;
          is_gift_for_her?: boolean;
          is_hero?: boolean;
          stock_qty?: number;
          merch_position?: number | null;
          new_arrival_position?: number | null;
          best_seller_position?: number | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: never;
          slug?: string;
          name?: string;
          category_id?: number;
          short_description?: string | null;
          description?: string | null;
          price?: number | null;
          materials?: string[];
          stones?: string[];
          colours?: string[];
          styles?: string[];
          closure?: string | null;
          chain_length?: string | null;
          care_override?: string | null;
          is_published?: boolean;
          is_new_arrival?: boolean;
          is_best_seller?: boolean;
          is_gift_for_her?: boolean;
          is_hero?: boolean;
          stock_qty?: number;
          merch_position?: number | null;
          new_arrival_position?: number | null;
          best_seller_position?: number | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      search_misses: {
        Row: {
          term: string;
          count: number;
          first_seen: string;
          last_seen: string;
        };
        Insert: {
          term: string;
          count?: number;
          first_seen?: string;
          last_seen?: string;
        };
        Update: {
          term?: string;
          count?: number;
          first_seen?: string;
          last_seen?: string;
        };
        Relationships: [
        ];
      };
      shipping_rules: {
        Row: {
          id: number;
          name: string;
          match_type: Database["public"]["Enums"]["shipping_match_type"];
          match_value: string | null;
          rate: number;
          free_above: number | null;
          est_days_min: number;
          est_days_max: number;
          priority: number;
          is_active: boolean;
        };
        Insert: {
          id?: never;
          name: string;
          match_type: Database["public"]["Enums"]["shipping_match_type"];
          match_value?: string | null;
          rate: number;
          free_above?: number | null;
          est_days_min?: number;
          est_days_max?: number;
          priority?: number;
          is_active?: boolean;
        };
        Update: {
          id?: never;
          name?: string;
          match_type?: Database["public"]["Enums"]["shipping_match_type"];
          match_value?: string | null;
          rate?: number;
          free_above?: number | null;
          est_days_min?: number;
          est_days_max?: number;
          priority?: number;
          is_active?: boolean;
        };
        Relationships: [
        ];
      };
      site_settings: {
        Row: {
          id: number;
          announcement_text: string | null;
          brand_story_text: string | null;
          brand_story_cta_label: string | null;
          brand_story_cta_url: string | null;
          whatsapp_number: string | null;
          support_email: string | null;
          support_phone: string | null;
          instagram_url: string | null;
          business_name: string;
          business_address: string | null;
          gstin: string | null;
          prices_include_gst: boolean;
          gst_rate: number;
          invoice_prefix: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          announcement_text?: string | null;
          brand_story_text?: string | null;
          brand_story_cta_label?: string | null;
          brand_story_cta_url?: string | null;
          whatsapp_number?: string | null;
          support_email?: string | null;
          support_phone?: string | null;
          instagram_url?: string | null;
          business_name?: string;
          business_address?: string | null;
          gstin?: string | null;
          prices_include_gst?: boolean;
          gst_rate?: number;
          invoice_prefix?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          announcement_text?: string | null;
          brand_story_text?: string | null;
          brand_story_cta_label?: string | null;
          brand_story_cta_url?: string | null;
          whatsapp_number?: string | null;
          support_email?: string | null;
          support_phone?: string | null;
          instagram_url?: string | null;
          business_name?: string;
          business_address?: string | null;
          gstin?: string | null;
          prices_include_gst?: boolean;
          gst_rate?: number;
          invoice_prefix?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      testimonials: {
        Row: {
          id: number;
          quote: string;
          author_name: string;
          location: string | null;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          id?: never;
          quote: string;
          author_name: string;
          location?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          id?: never;
          quote?: string;
          author_name?: string;
          location?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      assign_invoice_number: { Args: { p_order_id: string }; Returns: string };
      create_order: { Args: { payload: Json }; Returns: Json };
      expire_pending_orders: { Args: { p_older_than?: unknown }; Returns: number };
      is_admin: { Args: never; Returns: boolean };
      is_owner: { Args: never; Returns: boolean };
      log_search_miss: { Args: { p_term: string }; Returns: undefined };
      next_document_number: { Args: { p_kind: string; p_period: string }; Returns: number };
      pad_document_number: { Args: { n: number }; Returns: string };
      quote_shipping: { Args: { p_pincode: string; p_state: string; p_order_value: number }; Returns: { rule_id: number; fee: number; est_days_min: number; est_days_max: number }[] };
      restore_stock: { Args: { p_order_id: string }; Returns: boolean };
      search_products: { Args: { q: string; p_limit?: number; p_offset?: number }; Returns: { id: number; slug: string; name: string; price: number; rank: number; total: number }[] };
    };
    Enums: {
      admin_role: "owner" | "staff";
      image_role: "worn_closeup" | "lifestyle" | "product_only" | "detail" | "flat_lay" | "video";
      order_event_type: "status_change" | "payment" | "note";
      order_status: "pending_payment" | "placed" | "confirmed" | "packed" | "shipped" | "delivered" | "cancelled" | "returned" | "refunded";
      payment_method: "razorpay" | "gift_card";
      payment_status: "pending" | "paid" | "failed" | "refunded";
      relation_kind: "complete_the_look" | "cross_sell";
      shipping_match_type: "default" | "state" | "pincode_prefix";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
